import {chromium} from 'playwright';import{PDFDocument}from'pdf-lib';import{spawn}from'node:child_process';import{writeFileSync,mkdirSync}from'node:fs';
mkdirSync('/tmp/multi-tool-tests',{recursive:true});const pdf=await PDFDocument.create();pdf.addPage([300,400]);pdf.addPage([300,400]);writeFileSync('/tmp/multi-tool-tests/sample.pdf',await pdf.save());
const server=spawn('npm',['run','dev','--','--port','5178'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,2200));const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const context=await browser.newContext({acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();await page.goto('http://127.0.0.1:5178/');const image={name:'tiny.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFUlEQVQImWP8z8DwHwMDAwMjI2MAAA2zAgOHCdIBAAAAAElFTkSuQmCC','base64')};
let fails=[];
for(const id of ['compress','convert','resize','crop','rotate-image','image-pdf','grayscale','image-watermark','pdf-images','merge','split','extract','reorder','rotate-pdf','protect','unlock','change-password','delete-pages','reverse-pdf','duplicate-page','pdf-watermark','page-numbers','pdf-text','pdf-metadata','text-stats','case','json','password','duplicate-lines','url-encode','line-sort','line-reverse','find-replace','whitespace-clean','text-to-html','base64-text','markdown-preview','hash-text','hash-file','file-size','file-rename','zip-files','unzip-files','data-url','uuid','timestamp','color','aspect-ratio']){
try{await page.locator(`[data-id="${id}"]`).click();const imageIds=['compress','convert','resize','crop','rotate-image','image-pdf','grayscale','image-watermark'];const textIds=['text-stats','case','json','password','duplicate-lines','url-encode','line-sort','line-reverse','find-replace','whitespace-clean','text-to-html','base64-text','markdown-preview','hash-text','uuid','timestamp','color','aspect-ratio'];let file=imageIds.includes(id)?image:'/tmp/multi-tool-tests/sample.pdf';if(['hash-file','file-size','file-rename','zip-files','data-url'].includes(id))file={name:'tiny.txt',mimeType:'text/plain',buffer:Buffer.from('test')};if(id==='unzip-files')file='/tmp/multi-tool-tests/all-zip-files-files.zip';if(id==='merge')file=[{name:'a.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())},{name:'b.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())}];if(['unlock','change-password'].includes(id))file='/tmp/multi-tool-tests/protect-sample-protected.pdf';if(!textIds.includes(id))await page.locator('[name=files]').setInputFiles(file);const set=async(k,v)=>page.locator(`[name=${k}]`).fill(v);
if(id==='crop'){await set('width','1');await set('height','1')};if(id==='image-watermark'||id==='pdf-watermark')await set('text','DRAFT');if(id==='reorder')await set('pages','2,1');if(id==='extract'||id==='delete-pages')await set('pages','1');if(id==='duplicate-page')await set('page','1');if(id==='protect')await set('newPassword','test123');if(['unlock','change-password'].includes(id))await set('password','test123');if(id==='change-password')await set('newPassword','test456');if(id==='pdf-metadata')await set('title','Test document');if(['text-stats','case','duplicate-lines','url-encode','line-sort','line-reverse','find-replace','whitespace-clean','text-to-html','base64-text','markdown-preview','hash-text'].includes(id))await set('text','hello\nhello');if(id==='json')await set('text','{"a":1}');if(id==='find-replace')await set('find','hello');
const hasDownload=id!=='text-stats'&&id!=='case'&&id!=='password';const pending=hasDownload?page.waitForEvent('download',{timeout:20000}):null;await page.locator('#run').click();if(pending){const d=await pending;await d.saveAs(`/tmp/multi-tool-tests/all-${id}-${d.suggestedFilename()}`);}else await page.waitForFunction(()=>document.querySelector('#status').classList.contains('success')||document.querySelector('#status').classList.contains('error'));
const status=await page.locator('#status').innerText();if((await page.locator('#status').getAttribute('class')).includes('error'))throw Error(status);console.log('PASS',id,status);
}catch(e){console.log('FAIL',id,e.message);fails.push(id)}}await page.screenshot({path:'/tmp/multi-tool-tests/all-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/multi-tool-tests/all-mobile.png',fullPage:true});const expected={
'line-sort':'hello\nhello','find-replace':'\n','uuid':null,'color':'#368E7A','aspect-ratio':'800 × 450 px',
};for(const [id,needle] of Object.entries(expected)){const files=(await import('node:fs')).readdirSync('/tmp/multi-tool-tests');const match=files.find(f=>f.startsWith(`all-${id}-`));if(!match){fails.push(id+' output missing');continue;}const data=(await import('node:fs')).readFileSync('/tmp/multi-tool-tests/'+match,'utf8');if(needle&& !data.includes(needle)){fails.push(id+' content wrong');console.log('FAIL content',id,data.slice(0,80));}}console.log('FAILURES',fails);await browser.close();server.kill();if(fails.length)process.exitCode=1;
