import JSZip from 'jszip';
const makeBlob = (data,type='text/plain') => new Blob([data],{type});
const download = (data,name,type) => {const blob=data instanceof Blob?data:makeBlob(data,type);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
const slug = n=>n.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,72)||'file';
const textFile = (text,name)=>{download(text,name,'text/plain');return 'Result downloaded';};
const esc = v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatSize=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;
export async function runExtra(id,files,opts) {
  const raw=opts.text||'', lines=raw.split(/\r?\n/), file=files[0];
  if(id==='line-sort')return textFile(lines.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'})).join('\n'),'sorted-lines.txt');
  if(id==='line-reverse')return textFile(lines.reverse().join('\n'),'reversed-lines.txt');
  if(id==='find-replace'){if(!opts.find)throw Error('Enter text to find.');return textFile(raw.split(opts.find).join(opts.replace||''),'replaced.txt');}
  if(id==='whitespace-clean')return textFile(raw.split(/\r?\n/).map(line=>line.replace(/[\t ]+/g,' ').trim()).join('\n').replace(/\n{3,}/g,'\n\n'),'cleaned.txt');
  if(id==='text-to-html')return textFile(`<pre>${esc(raw)}</pre>`,'safe-text.html');
  if(id==='base64-text'){const value=opts.mode==='decode'?new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(raw.trim()),c=>c.charCodeAt(0))):(()=>{const b=new TextEncoder().encode(raw);let binary='';for(const n of b)binary+=String.fromCharCode(n);return btoa(binary)})();return textFile(value,'base64-text.txt');}
  if(id==='markdown-preview'){const lines=raw.split(/\r?\n/);let html='';for(const line of lines){const h=line.match(/^(#{1,6})\s+(.+)$/);html+=h?`<h${h[1].length}>${esc(h[2])}</h${h[1].length}>\n`:`<p>${esc(line)}</p>\n`;}return textFile(`<!doctype html><meta charset="utf-8"><title>Preview</title><main>${html}</main>`,'markdown-preview.html');}
  if(id==='hash-text'||id==='hash-file'){const data=id==='hash-file'?await file?.arrayBuffer():new TextEncoder().encode(raw);if(!data)throw Error('Choose a file.');const digest=await crypto.subtle.digest(opts.algorithm||'SHA-256',data);return textFile(Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join(''),`${id}-digest.txt`);}
  if(id==='file-size'){if(!files.length)throw Error('Choose files.');const report=files.map(f=>`${f.name}\t${formatSize(f.size)}\t${f.type||'unknown'}`).join('\n');return textFile(report,'file-size-report.txt');}
  if(id==='file-rename'){if(!files.length)throw Error('Choose files.');const prefix=(opts.prefix||'file').replace(/[^a-zA-Z0-9._-]/g,'-').slice(0,45);if(!prefix)throw Error('Enter a filename prefix.');const zip=new JSZip();files.forEach((f,i)=>{const ext=(f.name.match(/\.[^./]+$/)||[''])[0];zip.file(`${prefix}-${String(i+1).padStart(2,'0')}${ext}`,f)});download(await zip.generateAsync({type:'blob'}),'renamed-files.zip');return `${files.length} renamed files in ZIP`}
  if(id==='zip-files'){if(!files.length)throw Error('Choose files.');const zip=new JSZip();files.forEach(f=>zip.file(f.name,f));download(await zip.generateAsync({type:'blob'}),'files.zip');return `${files.length} files zipped`}
  if(id==='unzip-files'){if(!file)throw Error('Choose a ZIP file.');const zip=await JSZip.loadAsync(file),entries=Object.values(zip.files).filter(e=>!e.dir&&!e.name.startsWith('__MACOSX/'));if(entries.length>1000)throw Error('ZIP contains too many files (max 1000).');const out=new JSZip();for(const entry of entries){const safe=entry.name.split('/').pop().replace(/[^a-zA-Z0-9._-]/g,'-').replace(/^\.+/,'')||`file-${entries.indexOf(entry)+1}`;out.file(`${String(entries.indexOf(entry)+1).padStart(3,'0')}-${safe}`,await entry.async('uint8array'));}download(await out.generateAsync({type:'blob'}),'extracted-files.zip');return `${entries.length} files repacked for safe download`}
  if(id==='uuid'){const count=Number(opts.count);if(!Number.isInteger(count)||count<1||count>100)throw Error('Count must be 1–100.');return textFile(Array.from({length:count},()=>crypto.randomUUID()).join('\n'),'uuids.txt')}
  if(id==='timestamp'){const d=new Date(opts.date);if(Number.isNaN(d.getTime()))throw Error('Enter a valid date.');return textFile(`UTC: ${d.toISOString()}\nUnix seconds: ${Math.floor(d.getTime()/1000)}\nUnix milliseconds: ${d.getTime()}`,'timestamp.txt')}
  if(id==='color'){const hex=(opts.color||'').trim().replace(/^#/,'');if(!/^[0-9a-f]{6}$/i.test(hex))throw Error('Enter a six-digit hex color.');const channels=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16));return textFile(`#${hex.toUpperCase()}\nRGB: rgb(${channels.join(', ')})\nHSL: ${(()=>{let [r,g,b]=channels.map(c=>c/255),max=Math.max(r,g,b),min=Math.min(r,g,b),diff=max-min,l=(max+min)/2;if(!diff)return `hsl(0, 0%, ${Math.round(l*100)}%)`;let s=diff/(1-Math.abs(2*l-1)),h=max===r?((g-b)/diff)%6:max===g?(b-r)/diff+2:(r-g)/diff+4;return `hsl(${Math.round((h*60+360)%360)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`})()}`,'color.txt')}
  if(id==='aspect-ratio'){const w=Number(opts.width),h=Number(opts.height),newW=Number(opts.newWidth);if(![w,h,newW].every(n=>Number.isFinite(n)&&n>0))throw Error('Enter positive dimensions.');return textFile(`${Math.round(newW)} × ${Math.round(h*newW/w)} px`,'aspect-ratio.txt')}
  if(id==='data-url'){if(!file)throw Error('Choose a file.');if(file.size>1024*1024)throw Error('Data URLs are limited to 1 MB files.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});return textFile(data,`${slug(file.name)}-data-url.txt`)}
  throw Error('Tool not found.');
}
